# Generated by Django 2.0.7 on 2019-03-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=200)),
                ('header', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(),
        ),
    ]
