# Generated by Django 2.0.7 on 2019-03-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190301_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='header',
            new_name='chapter',
        ),
    ]
